language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - pip install coveralls tox-travis
install: "pip install -r requirements/devel.txt"
script: tox
after_success:
  - coveralls
notifications:
  email:
    on_failure: change
    on_success: change
