files:
  - source: /tcms/locale/django.pot
    translation: /tcms/locale/%two_letters_code%/LC_MESSAGES/django.po
    languages_mapping:
      two_letters_code:
        zh-CN: zh_CN
        zh-TW: zh_TW
